# Generated by Django 3.2.9 on 2021-11-23 11:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image_link',
            field=models.CharField(default=django.utils.timezone.now, help_text='link', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
