# Generated by Django 3.2.9 on 2021-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_num_of_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
